# Generated by Django 3.0.6 on 2020-06-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogImage',
            new_name='Poster',
        ),
    ]
