const userConstants = {

    REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

    GETME_REQUEST: "USERS_GETME_REQUEST",
    GETME_SUCCESS: "USERS_GETME_SUCCESS",
    GETME_FAILURE: "USERS_GETME_FAILURE",

    LOGOUT: "USERS_LOGOUT",
}
export default userConstants